' <auto-generated />
Imports System
Imports Persistence
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.VisualBasic

Namespace Global.Persistence.Migrations
    <DbContext(GetType(Context))>
    <Migration("20240430211227_002")>
    Partial Class _002
        ''' <inheritdoc />
        Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
            modelBuilder.
                HasAnnotation("ProductVersion", "8.0.4").
                HasAnnotation("Proxies:ChangeTracking", False).
                HasAnnotation("Proxies:CheckEquality", False).
                HasAnnotation("Proxies:LazyLoading", True)

            modelBuilder.Entity("Persistence.Models.City",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("Code").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(7).
                        HasColumnType("TEXT COLLATE NOCASE").
                        HasDefaultValue("")

                    b.Property(Of Guid)("Key").
                        HasColumnType("TEXT")

                    b.Property(Of String)("Name").
                        IsRequired().
                        ValueGeneratedOnAdd().
                        HasMaxLength(25).
                        HasColumnType("TEXT COLLATE NOCASE").
                        HasDefaultValue("")

                    b.HasKey("Id")

                    b.HasIndex("Code")

                    b.HasIndex("Name")

                    b.ToTable("Cities")
                End Sub)

            modelBuilder.Entity("Persistence.Models.User",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("AccessFailedCount").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ConcurrencyStamp").
                        IsConcurrencyToken().
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("Email").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Boolean)("EmailConfirmed").
                        HasColumnType("INTEGER")

                    b.Property(Of Boolean)("LockoutEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of DateTimeOffset?)("LockoutEnd").
                        HasColumnType("TEXT")

                    b.Property(Of String)("NormalizedEmail").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("NormalizedUserName").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("PasswordHash").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("PhoneNumber").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Boolean)("PhoneNumberConfirmed").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("SecurityStamp").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Boolean)("TwoFactorEnabled").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("UserName").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.HasKey("Id")

                    b.HasIndex("NormalizedEmail").
                        HasDatabaseName("EmailIndex")

                    b.HasIndex("NormalizedUserName").
                        IsUnique().
                        HasDatabaseName("UserNameIndex")

                    b.ToTable("AspNetUsers", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ConcurrencyStamp").
                        IsConcurrencyToken().
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("Name").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("NormalizedName").
                        HasMaxLength(256).
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.HasKey("Id")

                    b.HasIndex("NormalizedName").
                        IsUnique().
                        HasDatabaseName("RoleNameIndex")

                    b.ToTable("AspNetRoles", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ClaimType").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("ClaimValue").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Integer)("RoleId").
                        HasColumnType("INTEGER")

                    b.HasKey("Id")

                    b.HasIndex("RoleId")

                    b.ToTable("AspNetRoleClaims", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>",
                Sub(b)
                    b.Property(Of Integer)("Id").
                        ValueGeneratedOnAdd().
                        HasColumnType("INTEGER")

                    b.Property(Of String)("ClaimType").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("ClaimValue").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Integer)("UserId").
                        HasColumnType("INTEGER")

                    b.HasKey("Id")

                    b.HasIndex("UserId")

                    b.ToTable("AspNetUserClaims", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>",
                Sub(b)
                    b.Property(Of String)("LoginProvider").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("ProviderKey").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("ProviderDisplayName").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of Integer)("UserId").
                        HasColumnType("INTEGER")

                    b.HasKey("LoginProvider", "ProviderKey")

                    b.HasIndex("UserId")

                    b.ToTable("AspNetUserLogins", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>",
                Sub(b)
                    b.Property(Of Integer)("UserId").
                        HasColumnType("INTEGER")

                    b.Property(Of Integer)("RoleId").
                        HasColumnType("INTEGER")

                    b.HasKey("UserId", "RoleId")

                    b.HasIndex("RoleId")

                    b.ToTable("AspNetUserRoles", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>",
                Sub(b)
                    b.Property(Of Integer)("UserId").
                        HasColumnType("INTEGER")

                    b.Property(Of String)("LoginProvider").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("Name").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.Property(Of String)("Value").
                        HasColumnType("TEXT COLLATE NOCASE")

                    b.HasKey("UserId", "LoginProvider", "Name")

                    b.ToTable("AspNetUserTokens", DirectCast(Nothing, String))
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>",
                Sub(b)
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", Nothing).
                        WithMany().
                        HasForeignKey("RoleId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>",
                Sub(b)
                    b.HasOne("Persistence.Models.User", Nothing).
                        WithMany().
                        HasForeignKey("UserId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>",
                Sub(b)
                    b.HasOne("Persistence.Models.User", Nothing).
                        WithMany().
                        HasForeignKey("UserId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>",
                Sub(b)
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", Nothing).
                        WithMany().
                        HasForeignKey("RoleId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()

                    b.HasOne("Persistence.Models.User", Nothing).
                        WithMany().
                        HasForeignKey("UserId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                End Sub)

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>",
                Sub(b)
                    b.HasOne("Persistence.Models.User", Nothing).
                        WithMany().
                        HasForeignKey("UserId").
                        OnDelete(DeleteBehavior.Cascade).
                        IsRequired()
                End Sub)
        End Sub
    End Class
End Namespace
